/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Jasa;
import model.Transaksi;
import model.Pengeluaran;
import model.Harga;

/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
         // Array untuk menyimpan admin
    private static final ArrayList<Harga> hargaList = new ArrayList<>();
    private static final ArrayList<Jasa> jasaList = new ArrayList<>();
    private static final ArrayList<Transaksi> transaksiList = new ArrayList<>();
    private static final ArrayList<Pengeluaran> pengeluaranList = new ArrayList<>();

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlPengeluaran = new javax.swing.JPanel();
        txtTanggal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnInputPengeluaran = new javax.swing.JButton();
        txtKeterangan1 = new javax.swing.JTextField();
        txtNominal1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIdUsers1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtIdPengeluaran = new javax.swing.JTextField();
        pnlTransaksi = new javax.swing.JPanel();
        txtKeterangan = new javax.swing.JTextField();
        txtNominal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnInputTransaksi = new javax.swing.JButton();
        txtIdUsers = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        pnlJasa = new javax.swing.JPanel();
        txtIdJasa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnInputJasa = new javax.swing.JButton();
        txtKeterangan2 = new javax.swing.JTextField();
        txtNominal2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdUsers2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pnlHarga = new javax.swing.JPanel();
        txtIdHarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnInputHarga = new javax.swing.JButton();
        txtKeterangan3 = new javax.swing.JTextField();
        txtNominal3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtIdUsers3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnPengeluaran = new javax.swing.JButton();
        btnJenis = new javax.swing.JButton();
        btnJasa = new javax.swing.JButton();
        btnHarga = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 102, 153));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(pnlHome, "card6");

        pnlPengeluaran.setBackground(new java.awt.Color(255, 102, 153));
        pnlPengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        pnlPengeluaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTanggal.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });
        pnlPengeluaran.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 260, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Id Pengeluaran");
        pnlPengeluaran.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Tanggal");
        pnlPengeluaran.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 215, -1));

        btnInputPengeluaran.setText("INPUT");
        btnInputPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPengeluaranActionPerformed(evt);
            }
        });
        pnlPengeluaran.add(btnInputPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 91, 41));

        txtKeterangan1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPengeluaran.add(txtKeterangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 260, 30));

        txtNominal1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPengeluaran.add(txtNominal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 260, 30));

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Keterangan");
        pnlPengeluaran.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Nominal");
        pnlPengeluaran.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, -1));

        txtIdUsers1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPengeluaran.add(txtIdUsers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 260, 30));

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Id Users");
        pnlPengeluaran.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, -1));

        txtIdPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPengeluaranActionPerformed(evt);
            }
        });
        pnlPengeluaran.add(txtIdPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 260, 30));

        Content.add(pnlPengeluaran, "card3");

        pnlTransaksi.setBackground(new java.awt.Color(255, 102, 153));
        pnlTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKeterangan.setBackground(new java.awt.Color(255, 255, 255));
        pnlTransaksi.add(txtKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 258, 30));

        txtNominal.setBackground(new java.awt.Color(255, 255, 255));
        pnlTransaksi.add(txtNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 258, 30));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Keterangan");
        pnlTransaksi.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nominal");
        pnlTransaksi.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, -1));

        btnInputTransaksi.setText("INPUT");
        btnInputTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputTransaksiActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnInputTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 91, 41));

        txtIdUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlTransaksi.add(txtIdUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 258, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Id Users");
        pnlTransaksi.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, -1));

        Content.add(pnlTransaksi, "card4");

        pnlJasa.setBackground(new java.awt.Color(255, 102, 153));
        pnlJasa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdJasa.setBackground(new java.awt.Color(255, 255, 255));
        pnlJasa.add(txtIdJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 260, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Id Jasa");
        pnlJasa.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 167, -1));

        btnInputJasa.setText("INPUT");
        btnInputJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputJasaActionPerformed(evt);
            }
        });
        pnlJasa.add(btnInputJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 91, 41));

        txtKeterangan2.setBackground(new java.awt.Color(255, 255, 255));
        pnlJasa.add(txtKeterangan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, 30));

        txtNominal2.setBackground(new java.awt.Color(255, 255, 255));
        pnlJasa.add(txtNominal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 260, 30));

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Keterangan");
        pnlJasa.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nominal");
        pnlJasa.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 120, -1));

        txtIdUsers2.setBackground(new java.awt.Color(255, 255, 255));
        pnlJasa.add(txtIdUsers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 260, 30));

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Id Users");
        pnlJasa.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, -1));

        Content.add(pnlJasa, "card5");

        pnlHarga.setBackground(new java.awt.Color(255, 102, 153));
        pnlHarga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdHarga.setBackground(new java.awt.Color(255, 255, 255));
        pnlHarga.add(txtIdHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 260, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Harga");
        pnlHarga.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 167, -1));

        btnInputHarga.setText("INPUT");
        btnInputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputHargaActionPerformed(evt);
            }
        });
        pnlHarga.add(btnInputHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 91, 41));

        txtKeterangan3.setBackground(new java.awt.Color(255, 255, 255));
        pnlHarga.add(txtKeterangan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 258, 30));

        txtNominal3.setBackground(new java.awt.Color(255, 255, 255));
        pnlHarga.add(txtNominal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 258, 30));

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Keterangan");
        pnlHarga.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Nominal");
        pnlHarga.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 120, -1));

        txtIdUsers3.setBackground(new java.awt.Color(255, 255, 255));
        pnlHarga.add(txtIdUsers3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 258, 30));

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Id Users");
        pnlHarga.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, -1));

        Content.add(pnlHarga, "card2");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(204, 0, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("JASA HIKMAH");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(204, 2, 102));

        btnPengeluaran.setBackground(new java.awt.Color(255, 102, 153));
        btnPengeluaran.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPengeluaran.setForeground(new java.awt.Color(0, 0, 0));
        btnPengeluaran.setText("PENGELUARAN");
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        btnJenis.setBackground(new java.awt.Color(255, 102, 153));
        btnJenis.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnJenis.setForeground(new java.awt.Color(0, 0, 0));
        btnJenis.setText("JENIS");
        btnJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJenisActionPerformed(evt);
            }
        });

        btnJasa.setBackground(new java.awt.Color(255, 102, 153));
        btnJasa.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnJasa.setForeground(new java.awt.Color(0, 0, 0));
        btnJasa.setText("JASA");
        btnJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJasaActionPerformed(evt);
            }
        });

        btnHarga.setBackground(new java.awt.Color(255, 102, 153));
        btnHarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHarga.setForeground(new java.awt.Color(0, 0, 0));
        btnHarga.setText("HARGA");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 102, 153));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJenis)
                    .addComponent(btnJasa)
                    .addComponent(btnHarga)
                    .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHarga, btnJasa, btnJenis, btnPengeluaran});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJenis)
                .addGap(18, 18, 18)
                .addComponent(btnJasa)
                .addGap(18, 18, 18)
                .addComponent(btnHarga)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHarga, btnJasa, btnJenis, btnPengeluaran});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputHargaActionPerformed
        try {
            Harga objHarga = new Harga();
            objHarga.setId_harga(txtIdHarga.getText());
            objHarga.setKeterangan(txtKeterangan3.getText());
            int nominal = Integer.parseInt(txtNominal3.getText());
            objHarga.setNominal(nominal);
            objHarga.setId_users(txtIdUsers3.getText());
            objHarga.infoHargaPopup();
            // Menambahkan objek ke dalam ArrayList
            hargaList.add(objHarga);

            // Memberi konfirmasi bahwa harga berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Harga berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua harga yang ada di ArrayList
            StringBuilder allHarga = new StringBuilder("Daftar Harga:\n");
            for (Harga harga : hargaList) {
                allHarga.append("ID Harga: ").append(harga.getId_harga())
                        .append("\n Keterangan: ").append(harga.getKeterangan())
                        .append("\n Nominal: ").append(harga.getNominal())
                        .append("\n ID Users: ").append(harga.getId_users())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allHarga.toString(), 
                "Daftar Harga", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputHargaActionPerformed

    private void btnInputPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPengeluaranActionPerformed
        try {
            Pengeluaran objPengeluaran = new Pengeluaran();
            objPengeluaran.setId_pengeluaran(txtIdPengeluaran.getText());
            objPengeluaran.setTanggal(txtTanggal.getText());
            objPengeluaran.setKeterangan(txtKeterangan1.getText());
            int nominal = Integer.parseInt(txtNominal1.getText());
            objPengeluaran.setNominal(nominal);
            objPengeluaran.setId_users(txtIdUsers1.getText());
            objPengeluaran.infoPengeluaranPopup();
            // Menambahkan objek ke dalam ArrayList
            pengeluaranList.add(objPengeluaran);

            // Memberi konfirmasi bahwa pengeluaran berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Pengeluaran berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua pengeluaran yang ada di ArrayList
            StringBuilder allPengeluaran = new StringBuilder("Daftar Pengeluaran:\n");
            for (Pengeluaran pengeluaran : pengeluaranList) {
                allPengeluaran.append("ID Pengeluaran: ").append(pengeluaran.getId_pengeluaran())
                        .append("\n Tanggal: ").append(pengeluaran.getTanggal())
                        .append("\n Keterangan: ").append(pengeluaran.getKeterangan())
                        .append("\n Nominal: ").append(pengeluaran.getNominal())
                        .append("\n ID Users: ").append(pengeluaran.getId_users())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allPengeluaran.toString(), 
                "Daftar Pengeluaran", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnInputPengeluaranActionPerformed

    private void btnInputJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputJasaActionPerformed
        try {
            Jasa objJasa = new Jasa();
            objJasa.setId_jasa(txtIdJasa.getText());
            objJasa.setKeterangan(txtKeterangan2.getText());
            int nominal = Integer.parseInt(txtNominal2.getText());
            objJasa.setNominal(nominal);
            objJasa.setId_users(txtIdUsers2.getText());
            objJasa.infoJasaPopup();
            // Menambahkan objek ke dalam ArrayList
            jasaList.add(objJasa);

            // Memberi konfirmasi bahwa jasa berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Jasa berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua jasa yang ada di ArrayList
            StringBuilder allJasa = new StringBuilder("Daftar Jasa:\n");
            for (Jasa jasa : jasaList) {
                allJasa.append("ID Jasa: ").append(jasa.getId_jasa())
                        .append("\n Keterangan: ").append(jasa.getKeterangan())
                        .append("\n Nominal: ").append(jasa.getNominal())
                        .append("\n ID Users: ").append(jasa.getId_users())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allJasa.toString(), 
                "Daftar Jasa", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputJasaActionPerformed

    private void btnInputTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputTransaksiActionPerformed
        try {
            Transaksi objTransaksi = new Transaksi();
            objTransaksi.setKeterangan(txtKeterangan.getText());
            int nominal = Integer.parseInt(txtNominal.getText());
            objTransaksi.setNominal(nominal);
            objTransaksi.setId_users(txtIdUsers.getText());
            objTransaksi.infoTransaksiPopup();
            // Menambahkan objek ke dalam ArrayList
            transaksiList.add(objTransaksi);

        // Memberi konfirmasi bahwa transaksi berhasil ditambahkan
        JOptionPane.showMessageDialog(null, 
            "Jenis berhasil ditambahkan!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);

        // Menampilkan semua transaksi yang ada di ArrayList
        StringBuilder allTransaksi = new StringBuilder("Daftar Transaksi:\n");
        for (Transaksi transaksi : transaksiList) {
            allTransaksi.append("Keterangan : ").append(transaksi.getKeterangan())
                    .append("\n Nominal : ").append(transaksi.getNominal())
                    .append("\n ID Users : ").append(transaksi.getId_users())
                    .append("\n\n");
        }

        JOptionPane.showMessageDialog(null, allTransaksi.toString(), 
            "Daftar Jenis", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, 
            "Nominal harus berupa angka!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, 
            "Terjadi kesalahan: " + ex.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnInputTransaksiActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        Content.removeAll(); 
        Content.add(pnlPengeluaran);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void btnJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJenisActionPerformed
        Content.removeAll(); 
        Content.add(pnlTransaksi);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnJenisActionPerformed

    private void btnJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJasaActionPerformed
        Content.removeAll(); 
        Content.add(pnlJasa);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnJasaActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        Content.removeAll(); 
        Content.add(pnlHarga);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnHargaActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtIdPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPengeluaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputHarga;
    private javax.swing.JButton btnInputJasa;
    private javax.swing.JButton btnInputPengeluaran;
    private javax.swing.JButton btnInputTransaksi;
    private javax.swing.JButton btnJasa;
    private javax.swing.JButton btnJenis;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlHarga;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlJasa;
    private javax.swing.JPanel pnlPengeluaran;
    private javax.swing.JPanel pnlTransaksi;
    private javax.swing.JTextField txtIdHarga;
    private javax.swing.JTextField txtIdJasa;
    private javax.swing.JTextField txtIdPengeluaran;
    private javax.swing.JTextField txtIdUsers;
    private javax.swing.JTextField txtIdUsers1;
    private javax.swing.JTextField txtIdUsers2;
    private javax.swing.JTextField txtIdUsers3;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtKeterangan1;
    private javax.swing.JTextField txtKeterangan2;
    private javax.swing.JTextField txtKeterangan3;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JTextField txtNominal1;
    private javax.swing.JTextField txtNominal2;
    private javax.swing.JTextField txtNominal3;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
